name: take screenshots

on:
  workflow_call:
    inputs:
      urls:
        description: 'target URLs'
        required: true
        type: string
      update-snapshots:
        description: 'update snapshots'
        required: false
        type: boolean
        default: false

jobs:
  take-screenshots:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright@sha256:146d046a8d79a1b3a87596c4457b0b1c47f811bf4fc2cc1b99e873ae7f1cbbbd # v1.51.1-noble
    steps:
      - uses: actions/checkout@v4
        with:
          repository: sasaplus1-prototype/workflow-screenshot-with-playwright
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
      - run: npm ci
      - run: npm test ${{ inputs.update-snapshots != 'false' && '-- --update-snapshots' || '' }}
      - run: ls -alR
      - if: ${{ !cancel() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-results
          path: |
            playwright-report
            test-results
      - if: ${{ !cancel() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-screenshots
          path: screenshots
          if-no-files-found: ignore 
