name: test

on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      artifact-id: ${{ steps.artifact.outputs.artifact-id }}
      artifact-url: ${{ steps.artifact.outputs.artifact-url }}
      artifact-digest: ${{ steps.artifact.outputs.artifact-digest }}
    steps:
      - run: echo "Hello, World!"
      # - id: artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: scripts
      #     path: |
      #       playwright.config.ts
      #       global-setup.ts
      #       global-teardown.ts
      #     retention-days: 1
      #     include-hidden-files: true
  take-screenshots:
    needs:
      - test
    uses: sasaplus1-prototype/workflow-screenshot-with-playwright/.github/workflows/reusable-take-screenshots.yml@main
    # uses: ./.github/workflows/reusable-take-screenshots.yml
    with:
      urls: |
        https://example.com
        https://example.com/2
      update-snapshots: true
      # artifact-repository: sasaplus1-prototype/workflow-screenshot-with-playwright
      # artifact-name: scripts
      # artifact-id: ${{ needs.test.outputs.artifact-id }}
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
# post:
#   needs:
#     - take-screenshots
#   runs-on: ubuntu-latest
#   steps:
#     - uses: actions/download-artifact@v4
#       with:
